dubbo:
  registry:
    address: nacos://${NACOS_ADDR:localhost:18848}?username=${NACOS_USERNAME:nacos}&password=${NACOS_PASSWORD:nacos}
    parameters:
      namespace: ${NACOS_NAMESPACE:tenant-xxh6mimndoba}
      group: ${NACOS_GROUP:DEFAULT_GROUP}
      ignoreCheckKeys: username,password
  scan:
    base-packages: org.apache.dubbo.spring.boot.sample.provider.service
  protocol:
    port: 20880
    name: dubbo
  provider:
    parameters:
      paas-name: ${SERVICE_NAME:provider-demo}
      paas-ns: ${PAAS_NS:apm}
      service-type: Dubbo
      configs: ${NACOS_NAMESPACE:tenant-xxh6mimndoba}@${CONFIG_GROUP:DEFAULT_GROUP}@${SERVICE_NAME:provider-demo}-${PROFILE}