spring:
  cloud:
    discovery:
      master-backup:
        enabled: ${MASTER_BACKUP_ENABLED:true}
        serviceMetadataUpdatePeriod: ${MASTER_BACKUP_UPDATE_PERIOD:10}
      nacos-cluster:
        enabled: ${NACOS_CLUSTER_ENABLED:true}
        
management:
  endpoints:
    web:
      exposure:
        include: ${ENDPOINTS_INCLUDE:*}
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
      base-path: ${ENDPOINTS_BASE_PATH:/}

tenx:
  spring:
    cloud:
      sentinel:
        enabled: ${SENTINEL_ENABLED:true}

project:
  version: v1